/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Multiple: typeof import('./../components/element/Tree/multiple.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Single: typeof import('./../components/element/Tree/Single.vue')['default']
    SingleLazy: typeof import('./../components/element/Tree/SingleLazy.vue')['default']
    SkyCard: typeof import('./../components/SkyCard/index.vue')['default']
  }
}
